<?php
$data = array (
  0 => 
  array (
    'cat_id' => '3',
    'cat_name' => '日用超市',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  1 => 
  array (
    'cat_id' => '4',
    'cat_name' => '东北特产',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  2 => 
  array (
    'cat_id' => '1',
    'cat_name' => '进口鲜果',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '2',
    'goods_num' => 0,
  ),
  3 => 
  array (
    'cat_id' => '5',
    'cat_name' => '水产速递',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  4 => 
  array (
    'cat_id' => '19',
    'cat_name' => 'bb',
    'measure_unit' => '10',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  5 => 
  array (
    'cat_id' => '2',
    'cat_name' => '松仁乳',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '6',
  ),
  6 => 
  array (
    'cat_id' => '6',
    'cat_name' => '黑蒜系列',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => '5',
  ),
  7 => 
  array (
    'cat_id' => '7',
    'cat_name' => '储值卡',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  8 => 
  array (
    'cat_id' => '8',
    'cat_name' => '洗化用品',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => '7',
  ),
  9 => 
  array (
    'cat_id' => '9',
    'cat_name' => '进口食品',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => '6',
  ),
  10 => 
  array (
    'cat_id' => '10',
    'cat_name' => '咖啡',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  11 => 
  array (
    'cat_id' => '11',
    'cat_name' => '葡萄酒',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  12 => 
  array (
    'cat_id' => '17',
    'cat_name' => '蜂蜜',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  13 => 
  array (
    'cat_id' => '12',
    'cat_name' => '其他',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  14 => 
  array (
    'cat_id' => '13',
    'cat_name' => '食用油',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  15 => 
  array (
    'cat_id' => '14',
    'cat_name' => '大米',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => '11',
  ),
  16 => 
  array (
    'cat_id' => '15',
    'cat_name' => '面粉',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => '5',
  ),
  17 => 
  array (
    'cat_id' => '16',
    'cat_name' => '其他',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 0,
  ),
);
?>